CREATE DATABASE QLBD
GO
USE QLBD
GO


CREATE TABLE ACCOUNT
(
	USERNAME NCHAR(50),
	PASS NCHAR(50),
	TYPEACC TINYINT DEFAULT 0,
	NGAYLAP DATE,
	PRIMARY KEY (USERNAME)
)

CREATE TABLE CAUTHU
(
	MACT NCHAR(10) NOT NULL,
	MADB NCHAR(10) NOT NULL,
	HOTEN NVARCHAR(30),
	NGAYSINH DATE,
	DIACHI NVARCHAR(50),
	QUOCTICH NVARCHAR(20),
	SONAMKINHNGHIEM TINYINT,
	AVATAR NVARCHAR(500),
	SOBANTHANG SMALLINT DEFAULT 0,
	VITRI NVARCHAR(20),
	PRIMARY KEY (MACT, MADB)
)



CREATE TABLE HUANLUYENVIEN
(
	MAHLV NCHAR(10) NOT NULL,
	MADB NCHAR(10) NOT NULL,
	HOTEN NVARCHAR(30),
	NGAYSINH DATE,
	DIACHI NVARCHAR(50),
	QUOCTICH NVARCHAR(20),
	SONAMKINHNGHIEM TINYINT,
	AVATAR NVARCHAR(500),
	LOAIHLV BIT DEFAULT 0 ,
	PRIMARY KEY (MAHLV, MADB)
)

CREATE TABLE TRONGTAI
(
	MATT NCHAR(10) NOT NULL,
	HOTEN NVARCHAR(30),
	NGAYSINH DATE,
	DIACHI NVARCHAR(50),
	QUOCTICH NVARCHAR(20),
	SONAMKINHNGHIEM TINYINT,
	AVATAR NVARCHAR(500),
	LOAITRONGTAI BIT DEFAULT 0,
	PRIMARY KEY (MATT)
)

CREATE TABLE TRANDAU
(
	MATD NCHAR(10) NOT NULL,
	NGAYDIENRA DATETIME,
	DOI1 NCHAR(10),
	DOI2 NCHAR(10),
	SCORED1 SMALLINT DEFAULT 0,
	SCORED2 SMALLINT DEFAULT 0,
	TENSAN NVARCHAR(30),
	VONGDAU TINYINT,
	GHINHAN BIT DEFAULT 0,
	PRIMARY KEY (MATD)
)


CREATE TABLE BANTHANG
(
	MACT NCHAR(10) NOT NULL,
	MADB NCHAR(10) NOT NULL,
	MATD NCHAR(10) NOT NULL,
	PHUTGHIBAN TINYINT NOT NULL,
	LOAIBT NCHAR(1),
	PRIMARY KEY (MACT,MADB,MATD,PHUTGHIBAN)
)

CREATE TABLE DOIBONG
(
	MADB NCHAR(10) NOT NULL,
	TENDOIBONG NVARCHAR(30),
	SOLUONGCAUTHU TINYINT DEFAULT 0,
	TENSANNHA NVARCHAR(30),
	TINHTHANH NVARCHAR(30),
	NGAYTHANHLAP DATE,
	SOBANTHANG SMALLINT DEFAULT 0,
	SOBANTHUA SMALLINT DEFAULT 0,
	TONGDIEM SMALLINT DEFAULT 0,
	PRIMARY KEY (MADB)
)

CREATE TABLE TRANDAU_TRONGTAI
(
	MATD NCHAR(10) NOT NULL,
	MATT NCHAR(10) NOT NULL,
	PRIMARY KEY (MATD, MATT)
)

-- UPDATE 28-12
CREATE TABLE LOAIBANTHANG
(
	MABT NCHAR(1),
	TENBT NCHAR(30),
	PRIMARY KEY(MABT)
)

ALTER TABLE BANTHANG
ADD CONSTRAINT FK_BANTHANG_LOAIBANTHANG
FOREIGN KEY (LOAIBT)
REFERENCES LOAIBANTHANG(MABT)

-----------

ALTER TABLE CAUTHU
ADD CONSTRAINT FK_CAUTHU_DOIBONG
FOREIGN KEY (MADB)
REFERENCES DOIBONG(MADB)

ALTER TABLE HUANLUYENVIEN
ADD CONSTRAINT FK_HUANLUYENVIEN_DOIBONG
FOREIGN KEY (MADB)
REFERENCES DOIBONG(MADB)

ALTER TABLE BANTHANG
ADD CONSTRAINT FK_BANTHANG_CAUTHU
FOREIGN KEY (MACT,MADB)
REFERENCES CAUTHU(MACT,MADB)

ALTER TABLE BANTHANG
ADD CONSTRAINT FK_BANGTHANG_DOIBONG
FOREIGN KEY (MADB)
REFERENCES DOIBONG(MADB)

ALTER TABLE BANTHANG
ADD CONSTRAINT FK_BANTHANG_TRANDAU
FOREIGN KEY (MATD)
REFERENCES TRANDAU(MATD)

ALTER TABLE TRANDAU_TRONGTAI
ADD CONSTRAINT FK_TRANDAU_TRONGTAI_TRANDAU
FOREIGN KEY (MATD)
REFERENCES TRANDAU(MATD)

ALTER TABLE TRANDAU_TRONGTAI
ADD CONSTRAINT FK_TRANDAU_TRONGTAI_TRONGTAI
FOREIGN KEY (MATT)
REFERENCES TRONGTAI(MATT)


ALTER TABLE TRANDAU
ADD CONSTRAINT FK_TRANDAU_DOIBONG1
FOREIGN KEY (DOI1)
REFERENCES DOIBONG(MADB)


ALTER TABLE TRANDAU
ADD CONSTRAINT FK_TRANDAU_DOIBONG2
FOREIGN KEY (DOI2)
REFERENCES DOIBONG(MADB)



--- TẠO TABLE QUYDINH
CREATE TABLE QUYDINH
(
	MAQD INT,
	PLAYER_AGE_MAX INT,
	PLAYER_AGE_MIN INT,
	PLAYER_NUM_MAX INT,
	PLAYER_NUM_MIN INT,
	PLAYER_FOREIGN_MAX INT,
	THOI_DIEM_GHI_BAN_MAX INT,
	SCORE_THANG INT,
	SCORE_THUA INT,
	SCORE_HOA INT,
	PRIMARY KEY(MAQD)
)